version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  shellcheck: circleci/shellcheck@2.2.4

jobs:
  prepare-docker-file:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run: 
          command: |
            mkdir bucket && cat \<<EOF > bucket/.dockercfg
            {
              "auths": {
                "https://registry.gitlab.com": {
                  "auth": "$DOCKER_AUTH"
                }
              }
            }
      - aws-s3/copy:
          from: bucket/.dockercfg
          to: 's3://elasticbeanstalk-us-east-1-544475008658/docker-react/'
      - run: 
          command: |
            cat \<<EOF > bucket/Dockerrun.aws.json 
            {
              "AWSEBDockerrunVersion": "1",
              "Authentication": {
                "bucket": "elasticbeanstalk-us-east-1-544475008658",
                "key": "docker-react/.dockercfg"
              },
              "Image": {
                "Name": "registry.gitlab.com/rajtopale/docker_registry/docker-react:0.1.4",
                "Update": "true"
              },
              "Ports": [
                {
                  "ContainerPort": "3000"
                }
              ],
              "Logging": "/var/log/nginx"
            }
      - aws-s3/copy:
          from: bucket/Dockerrun.aws.json
          to: 's3://elasticbeanstalk-us-east-1-544475008658/docker-react/'

workflows:
  version: 2
  elastic-beanstalk-workflow:
    jobs:
      - shellcheck/check
      - prepare-docker-file:
          context: AWS
          requires:
            - shellcheck/check
          filters:
            branches:
              only:
                - master
          



