version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  shellcheck: circleci/shellcheck@2.2.4
  aws-cli: circleci/aws-cli@2.0

jobs:
  build:
    working_directory: ~/repo
    environment:
      IMAGE_NAME: registry.gitlab.com/rajtopale/docker_registry/docker-react
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $IMAGE_NAME:$TAG .
          echo $DOCKER_PASS | docker login registry.gitlab.com -u $DOCKER_USER --password-stdin
          docker push $IMAGE_NAME:$TAG
  push-config-files:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run: 
          command: |
            mkdir bucket && cat \<<EOF > bucket/dockercfg
            {
              "auths": {
                "https://registry.gitlab.com": {
                  "auth": "$DOCKER_AUTH"
                }
              }
            }
      - run: 
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            cat \<<EOF > bucket/$TAG-Dockerrun.aws.json 
            {
              "AWSEBDockerrunVersion": "1",
              "Authentication": {
                "bucket": "elasticbeanstalk-us-east-1-544475008658",
                "key": "docker-react/dockercfg"
              },
              "Image": {
                "Name": "registry.gitlab.com/rajtopale/docker_registry/docker-react:$TAG"
              },
              "Ports": [
                {
                  "ContainerPort": "3000"
                }
              ]
            }
            EOF
            ls -l bucket
      - aws-s3/copy:
          from: bucket/
          to: 's3://elasticbeanstalk-us-east-1-544475008658/docker-react/'

workflows:
  version: 2
  elastic-beanstalk-workflow:
    jobs:
      - shellcheck/check
      - push-config-files:
          context: AWS
          requires:
            - shellcheck/check
          filters:
            branches:
              only:
                - master
          



